### PR TITLE
Releasing v3.3.0

### PR DESCRIPTION
**Pull request by azizk**
Solving some last issues and checking everything. :slightly_smiling_face:

Btw, how do you publish the package? Just merge into `main`? Or do you also create a PR in the PackageControl project?

### CODE REVIEW

**Comment by princemaple** [comment]
Merge the PR and then make a GitHub release, doing this will also tag it. Package Control will pick up the new tag.

**Comment by princemaple** [comment]
Happy with this now? :)

**Comment by azizk** [comment]
> Happy with this now? :)

Not quite, but I'm getting there. The behaviour when calling `mix test` isn't right or convenient anymore. :face_with_diagonal_mouth:

**Comment by azizk** [comment]
Closing this to release version 4.0.0 instead.

**Pull request closed without merging**
